# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: ssh
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: vim
# Aliases allow you to create nicknames for gh commands
aliases:
    bugs: issue list --label bugs
    enhancements: issue list --label enhancement
    dep-updates: pr list --label dependencies
    workflows: |-
      !gh api /repos/:owner/:repo/actions/workflows
    list-failed-builds: |-
      !gh api repos/:owner/:repo/actions/runs --paginate | jq -r ".workflow_runs[] | select(.conclusion == \"failure\")"
    remove-failed-builds: |-
      !gh list-failed-builds | jq -r ".id" | xargs -t -P4 -I{} gh remove-workflow-run {}
    remove-workflow-run: |-
      !gh api repos/:owner/:repo/actions/runs/$1 -X DELETE >/dev/null
