# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: ssh
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: vim
# Aliases allow you to create nicknames for gh commands
aliases:
    bugs: issue list --label="bugs"
    workflows: |-
      !gh api /repos/:owner/:repo/actions/workflows
    remove-failed-builds: '!gh list-failed-builds $1 | jq -r ".id" | xargs -t -I{} gh remove-workflow-run $1 {}'
    list-failed-builds: '!gh api repos/$1/actions/runs --paginate | jq -r ".workflow_runs[] | select(.conclusion == \"failure\")"'
    remove-workflow-run: '!gh api repos/$1/actions/runs/$2 -X DELETE >/dev/null'
